version: "3"
services:
  app:
    build: .
    restart: always
    env_file: .env
    network_mode: host
    image: brew
  rearq-worker:
    network_mode: host
    env_file: .env
    image: brew
    restart: always
    depends_on:
      - app
    command: rearq brew.tasks:rearq worker -t
